#pragma once

#define INSP_MODULE_NONE				_T("NONE")
#define INSP_MODULE_ERROR				_T("ERROR")
#define INSP_MODULE_CELL_LOADING		CELL_LOADING
#define INSP_MODULE_MTP_WRITE			MTP_WRITE
#define INSP_MODULE_MTP_VERIFY			MTP_VERIFY
#define INSP_MODULE_WHITE_CURRENT		WHITE_CURRENT_CHECK
#define INSP_MODULE_SLEEP_CURRENT		SLEEP_CURRENT_CHECK
#define INSP_MODULE_HLPM_CURRENT		HLPM_CURRENT_CHECK
#define INSP_MODULE_TSP_START			TSP_START
#define INSP_MODULE_EVT_VERSION_CHECK	EVT_VERSION_CHECK
#define INSP_MODULE_TE_CHECK			TE_CHECK
#define INSP_MODULE_ID_CHECK			ID_CHECK
#define INSP_MODULE_OTP_REG_CHECK		OTP_REG_CHECK
#define INSP_MODULE_ICT_TEST			ICT_TEST
#define INSP_MODULE_COPR_ICT_TEST		COPR_ICT_TEST
#define INSP_MODULE_POC_ERROR_CHECK		POC_ERROR_CHECK
#define INSP_MODULE_DDI_BLOCK_TEST		DDI_BLOCK_TEST
#define INSP_MODULE_OPTION_CHECK2		OPTION_CHECK2
#define INSP_MODULE_OPTION_CHECK3		OPTION_CHECK3
#define INSP_MODULE_OPTION_CHECK4		OPTION_CHECK4
#define INSP_MODULE_OPTION_CHECK5		OPTION_CHECK5
#define INSP_MODULE_OPTION_CHECK6		OPTION_CHECK6
#define INSP_MODULE_OPTION_CHECK7		OPTION_CHECK7
#define INSP_MODULE_OPTION_CHECK8		OPTION_CHECK8
#define INSP_MODULE_OPTION_CHECK9		OPTION_CHECK9
#define INSP_MODULE_OPTION_CHECK10		OPTION_CHECK10
