#include "StdAfx.h"
#include "IOParamBank.h"

#ifdef _DEBUG
#undef THIS_FILE
static char THIS_FILE[]=__FILE__;
#define new DEBUG_NEW
#endif

CIOParam::CIOParam(void)
{
	m_Check = CHECK_TYPE_A;
}


CIOParam::~CIOParam(void)
{
}

BOOL CIOParam::ReturnOn()
{
	// Input일 경우 B접은 Off되어야 감지. Output일 경우 Off해야 동작
	// Input일 경우 A접은 On되어야 감지. Output일 경우 On해야 동작
	return (m_Check == CHECK_TYPE_A) ? TRUE:FALSE;
}

BOOL CIOParam::ReturnOff()
{
	// Input일 경우 B접은 Off되어야 감지. Output일 경우 Off해야 동작
	// Input일 경우 A접은 On되어야 감지. Output일 경우 On해야 동작
	return (m_Check == CHECK_TYPE_A) ? FALSE:TRUE;
}

BOOL CIOParam::ReturnFrom( VAC_STATE vac )
{
	return vac == VAC_ON ? ReturnOn():ReturnOff();
}

BOOL CIOParam::ReturnFrom( CYL_STATE cyl )
{
	if( (cyl == CYL_FWD) && (cyl == CYL_DOWN) )
		return ReturnOn();
	else
		return ReturnOff();
}

BOOL CIOParam::GetIOCheck(ONOFF value)
{
	BOOL bRet = FALSE;
	if(value == ON)
	{
		bRet = ReturnOn();
	}
	else
	{
		bRet = ReturnOff();
	}
	//return value == ON ? ReturnOn():ReturnOff();
	return bRet;
}

BOOL CIOParam::GetIOCheck(BOOL bValue)
{
	BOOL bRet = FALSE;
	if(bValue == TRUE)
	{
		bRet = ReturnOn();
	}
	else
	{
		bRet = ReturnOff();
	}
	//return value == ON ? ReturnOn():ReturnOff();
	return bRet;
}








CIOParamBank::CIOParamBank( void )
{

}

CIOParamBank::~CIOParamBank( void )
{

}

void CIOParamBank::InitializeIOParam()
{
	// 미사용 I/O도 있으니 기본 I/O No.로 일단 이름지어놓는다
	for(int i = 0; i < MAX_IN_ID; i++)
	{
		m_In[i].m_strIOAddress.Format(_T("X_%03X"), i);
		m_In[i].m_strIOName.Format(_T("X_%03X"), i);
	}
	for(int i = 0; i < MAX_OUT_ID; i++)
	{
		m_Out[i].m_strIOAddress.Format(_T("Y_%03X"), i);
		m_Out[i].m_strIOName.Format(_T("Y_%03X"), i);
	}

	InitializeIOParam_IN();
	InitializeIOParam_OUT();
}

void CIOParamBank::InitializeIOParam_IN()
{
	//X0000~X000F
	m_In[X_AUTO_TEACH_KEY].m_strIOName=_T("X_AUTO_TEACH_KEY");m_In[X_AUTO_TEACH_KEY].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_OP_RESET_SW].m_strIOName=_T("X_OP_RESET_SW");m_In[X_OP_RESET_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_EMS_SWITCH_1].m_strIOName=_T("X_EMS_SWITCH_1");m_In[X_EMS_SWITCH_1].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_EMS_SWITCH_2].m_strIOName=_T("X_EMS_SWITCH_2");m_In[X_EMS_SWITCH_2].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_LIGHT_CURTAIN].m_strIOName=_T("X_SHUTTLE_1_LIGHT_CURTAIN");m_In[X_SHUTTLE_1_LIGHT_CURTAIN].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_LIGHT_CURTAIN].m_strIOName=_T("X_SHUTTLE_2_LIGHT_CURTAIN");m_In[X_SHUTTLE_2_LIGHT_CURTAIN].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_PDT_LIGHT_CURTAIN].m_strIOName=_T("X_PDT_LIGHT_CURTAIN");m_In[X_PDT_LIGHT_CURTAIN].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_UTIL_BOX_TEMP_ALARM].m_strIOName=_T("X_UTIL_BOX_TEMP_ALARM");m_In[X_UTIL_BOX_TEMP_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_UTIL_BOX_FIRE_ALARM].m_strIOName=_T("X_UTIL_BOX_FIRE_ALARM");m_In[X_UTIL_BOX_FIRE_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SNC_SMPS1_ON_CHECK].m_strIOName=_T("X_SNC_SMPS1_ON_CHECK");m_In[X_SNC_SMPS1_ON_CHECK].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SNC_SMPS2_ON_CHECK].m_strIOName=_T("X_SNC_SMPS2_ON_CHECK");m_In[X_SNC_SMPS2_ON_CHECK].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_SAFETY_DC_POWER_ON_CHECK].m_strIOName=_T("X_SAFETY_DC_POWER_ON_CHECK");m_In[X_SAFETY_DC_POWER_ON_CHECK].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_GPS_POWER_DOWN].m_strIOName=_T("X_GPS_POWER_DOWN");m_In[X_GPS_POWER_DOWN].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_MC_ON_CHECK].m_strIOName=_T("X_MC_ON_CHECK");m_In[X_MC_ON_CHECK].m_Check=CIOParam::CHECK_TYPE_A;
	
	//X010~X01F
	m_In[X_Main_BOX_FAN1_ALARM].m_strIOName=_T("X_Main_BOX_FAN1_ALARM");m_In[X_Main_BOX_FAN1_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_Main_BOX_FAN2_ALARM].m_strIOName=_T("X_Main_BOX_FAN2_ALARM");m_In[X_Main_BOX_FAN2_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_Main_BOX_FAN3_ALARM].m_strIOName=_T("X_Main_BOX_FAN3_ALARM");m_In[X_Main_BOX_FAN3_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_Main_BOX_FAN4_ALARM].m_strIOName=_T("X_Main_BOX_FAN4_ALARM");m_In[X_Main_BOX_FAN4_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_FRONT_DOOR1_SENSOR].m_strIOName=_T("X_FRONT_DOOR1_SENSOR");m_In[X_FRONT_DOOR1_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_FRONT_DOOR2_SENSOR].m_strIOName=_T("X_FRONT_DOOR2_SENSOR");m_In[X_FRONT_DOOR2_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_RIGNT_DOOR_SENSOR].m_strIOName=_T("X_RIGNT_DOOR_SENSOR");m_In[X_RIGNT_DOOR_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_BACK_DOOR1_SENSOR].m_strIOName=_T("X_BACK_DOOR1_SENSOR");m_In[X_BACK_DOOR1_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_HOT_LINE_PDT_ALIVE].m_strIOName=_T("X_HOT_LINE_PDT_ALIVE");m_In[X_HOT_LINE_PDT_ALIVE].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_HOT_LINE_PDT_EMERGENCY].m_strIOName=_T("X_HOT_LINE_PDT_EMERGENCY");m_In[X_HOT_LINE_PDT_EMERGENCY].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_HOT_LINE_PDT_NET_READY].m_strIOName=_T("X_HOT_LINE_PDT_NET_READY");m_In[X_HOT_LINE_PDT_NET_READY].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_HOT_LINE_PDT_DOOR_OPEN].m_strIOName=_T("X_HOT_LINE_PDT_DOOR_OPEN");m_In[X_HOT_LINE_PDT_DOOR_OPEN].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_HOT_LINE_PDT_INTERLOCK].m_strIOName=_T("X_HOT_LINE_PDT_INTERLOCK");m_In[X_HOT_LINE_PDT_INTERLOCK].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_HOT_LINE_PDT_INTERACTIVE_2].m_strIOName=_T("X_HOT_LINE_PDT_INTERACTIVE_2");m_In[X_HOT_LINE_PDT_INTERACTIVE_2].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_HOT_LINE_PDT_INTERACTIVE_3].m_strIOName=_T("X_HOT_LINE_PDT_INTERACTIVE_3");m_In[X_HOT_LINE_PDT_INTERACTIVE_3].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_HOT_LINE_PDT_SUB_EMO].m_strIOName=_T("X_HOT_LINE_PDT_SUB_EMO");m_In[X_HOT_LINE_PDT_SUB_EMO].m_Check=CIOParam::CHECK_TYPE_A;
	
	//X0020~X002F
	m_In[X_SHUTTLE_1_VACCUM_ON_SW].m_strIOName=_T("X_SHUTTLE_1_VACCUM_ON_SW");m_In[X_SHUTTLE_1_VACCUM_ON_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_VACCUM_OFF_SW].m_strIOName=_T("X_SHUTTLE_1_VACCUM_OFF_SW");m_In[X_SHUTTLE_1_VACCUM_OFF_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_PATTERN_BACK_SW].m_strIOName=_T("X_SHUTTLE_1_PATTERN_BACK_SW");m_In[X_SHUTTLE_1_PATTERN_BACK_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_PATTERN_NEXT_SW].m_strIOName=_T("X_SHUTTLE_1_PATTERN_NEXT_SW");m_In[X_SHUTTLE_1_PATTERN_NEXT_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_PATTERN_ONOFF_SW].m_strIOName=_T("X_SHUTTLE_1_PATTERN_ONOFF_SW");m_In[X_SHUTTLE_1_PATTERN_ONOFF_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_VACCUM_READY_SW].m_strIOName=_T("X_SHUTTLE_1_VACCUM_READY_SW");m_In[X_SHUTTLE_1_VACCUM_READY_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_PATTERN_READY_SW].m_strIOName=_T("X_SHUTTLE_1_PATTERN_READY_SW");m_In[X_SHUTTLE_1_PATTERN_READY_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_VACCUM_ON_SW].m_strIOName=_T("X_SHUTTLE_2_VACCUM_ON_SW");m_In[X_SHUTTLE_2_VACCUM_ON_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_VACCUM_OFF_SW].m_strIOName=_T("X_SHUTTLE_2_VACCUM_OFF_SW");m_In[X_SHUTTLE_2_VACCUM_OFF_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_PATTERN_BACK_SW].m_strIOName=_T("X_SHUTTLE_2_PATTERN_BACK_SW");m_In[X_SHUTTLE_2_PATTERN_BACK_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_PATTERN_NEXT_SW].m_strIOName=_T("X_SHUTTLE_2_PATTERN_NEXT_SW");m_In[X_SHUTTLE_2_PATTERN_NEXT_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_PATTERN_ONOFF_SW].m_strIOName=_T("X_SHUTTLE_2_PATTERN_ONOFF_SW");m_In[X_SHUTTLE_2_PATTERN_ONOFF_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_VACCUM_READY_SW].m_strIOName=_T("X_SHUTTLE_2_VACCUM_READY_SW");m_In[X_SHUTTLE_2_VACCUM_READY_SW].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_PATTERN_READY_SW].m_strIOName=_T("X_SHUTTLE_2_PATTERN_READY_SW");m_In[X_SHUTTLE_2_PATTERN_READY_SW].m_Check=CIOParam::CHECK_TYPE_A;
	
	//X0040~X004F
	m_In[X_C_BOX_A_FAN1_ALARM].m_strIOName=_T("X_C_BOX_A_FAN1_ALARM");m_In[X_C_BOX_A_FAN1_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_C_BOX_A_FAN2_ALARM].m_strIOName=_T("X_C_BOX_A_FAN2_ALARM");m_In[X_C_BOX_A_FAN2_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_OP_PC_FAN1_ALARM].m_strIOName=_T("X_OP_PC_FAN1_ALARM");m_In[X_OP_PC_FAN1_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_OP_PC_FAN2_ALARM].m_strIOName=_T("X_OP_PC_FAN2_ALARM");m_In[X_OP_PC_FAN2_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_OP_PC_FAN3_ALARM].m_strIOName=_T("X_OP_PC_FAN3_ALARM");m_In[X_OP_PC_FAN3_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_OP_PC_FAN4_ALARM].m_strIOName=_T("X_OP_PC_FAN4_ALARM");m_In[X_OP_PC_FAN4_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_C_BOX_A_TEMP_ALARM].m_strIOName=_T("X_C_BOX_A_TEMP_ALARM");m_In[X_C_BOX_A_TEMP_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_C_BOX_A_FIRE_ALARM].m_strIOName=_T("X_C_BOX_A_FIRE_ALARM");m_In[X_C_BOX_A_FIRE_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_OP_PC_TEMP_ALARM].m_strIOName=_T("X_OP_PC_TEMP_ALARM");m_In[X_OP_PC_TEMP_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_OP_PC_FIRE_ALARM].m_strIOName=_T("X_OP_PC_FIRE_ALARM");m_In[X_OP_PC_FIRE_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_EFU_ALARM].m_strIOName=_T("X_EFU_ALARM");m_In[X_EFU_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_TABLE_STO1].m_strIOName=_T("X_SHUTTLE_TABLE_STO1");m_In[X_SHUTTLE_TABLE_STO1].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_TABLE_STO2].m_strIOName=_T("X_SHUTTLE_TABLE_STO2");m_In[X_SHUTTLE_TABLE_STO2].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_TILTING_DOWN].m_strIOName=_T("X_SHUTTLE_1_TILTING_DOWN");m_In[X_SHUTTLE_1_TILTING_DOWN].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_TILTING_UP].m_strIOName=_T("X_SHUTTLE_1_TILTING_UP");m_In[X_SHUTTLE_1_TILTING_UP].m_Check=CIOParam::CHECK_TYPE_A;
	
	//X0050~X005F
	m_In[X_C_BOX_B_FAN1_ALARM].m_strIOName=_T("X_C_BOX_B_FAN1_ALARM");m_In[X_C_BOX_B_FAN1_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_C_BOX_B_FAN2_ALARM].m_strIOName=_T("X_C_BOX_B_FAN2_ALARM");m_In[X_C_BOX_B_FAN2_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_ALIGN_PG_PC_FAN1_ALARM].m_strIOName=_T("X_ALIGN_PG_PC_FAN1_ALARM");m_In[X_ALIGN_PG_PC_FAN1_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_ALIGN_PG_PC_FAN2_ALARM].m_strIOName=_T("X_ALIGN_PG_PC_FAN2_ALARM");m_In[X_ALIGN_PG_PC_FAN2_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_ALIGN_PG_PC_FAN3_ALARM].m_strIOName=_T("X_ALIGN_PG_PC_FAN3_ALARM");m_In[X_ALIGN_PG_PC_FAN3_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_ALIGN_PG_PC_FAN4_ALARM].m_strIOName=_T("X_ALIGN_PG_PC_FAN4_ALARM");m_In[X_ALIGN_PG_PC_FAN4_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_C_BOX_B_TEMP_ALARM].m_strIOName=_T("X_C_BOX_B_TEMP_ALARM");m_In[X_C_BOX_B_TEMP_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_C_BOX_B_FIRE_ALARM].m_strIOName=_T("X_C_BOX_B_FIRE_ALARM");m_In[X_C_BOX_B_FIRE_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_ALIGN_PG_PC_TEMP_ALARM].m_strIOName=_T("X_ALIGN_PG_PC_TEMP_ALARM");m_In[X_ALIGN_PG_PC_TEMP_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_ALIGN_PG_PC_FIRE_ALARM].m_strIOName=_T("X_ALIGN_PG_PC_FIRE_ALARM");m_In[X_ALIGN_PG_PC_FIRE_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_TILTING_DOWN].m_strIOName=_T("X_SHUTTLE_2_TILTING_DOWN");m_In[X_SHUTTLE_2_TILTING_DOWN].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_TILTING_UP].m_strIOName=_T("X_SHUTTLE_2_TILTING_UP");m_In[X_SHUTTLE_2_TILTING_UP].m_Check=CIOParam::CHECK_TYPE_A;
	
	//X0060~X006F
	//m_In[X_SHUTTLE_1_MANIFOLD_PRESSURE_SENSOR].m_strIOName=_T("X_SHUTTLE_1_MANIFOLD_PRESSURE_SENSOR");m_In[X_SHUTTLE_1_MANIFOLD_PRESSURE_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_SHUTTLE_1_EJECTOR_PRESSURE_SENSOR].m_strIOName=_T("X_SHUTTLE_1_EJECTOR_PRESSURE_SENSOR");m_In[X_SHUTTLE_1_EJECTOR_PRESSURE_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_VACCUM_ON_SENSOR].m_strIOName=_T("X_SHUTTLE_1_VACCUM_ON_SENSOR");m_In[X_SHUTTLE_1_VACCUM_ON_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_1_FPCB_VACCUM_ON_SENSOR].m_strIOName=_T("X_SHUTTLE_1_FPCB_VACCUM_ON_SENSOR");m_In[X_SHUTTLE_1_FPCB_VACCUM_ON_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_ONIZER_1_PRESSURE_SENSOR].m_strIOName=_T("X_ONIZER_1_PRESSURE_SENSOR");m_In[X_ONIZER_1_PRESSURE_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_IONIZER_1_ALARM].m_strIOName=_T("X_IONIZER_1_ALARM");m_In[X_IONIZER_1_ALARM].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_MAIN_AIR_DOWN].m_strIOName=_T("X_MAIN_AIR_DOWN");m_In[X_MAIN_AIR_DOWN].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_SHUTTLE_2_MANIFOLD_PRESSURE_SENSOR].m_strIOName=_T("X_SHUTTLE_2_MANIFOLD_PRESSURE_SENSOR");m_In[X_SHUTTLE_2_MANIFOLD_PRESSURE_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_SHUTTLE_2_EJECTOR_PRESSURE_SENSOR].m_strIOName=_T("X_SHUTTLE_2_EJECTOR_PRESSURE_SENSOR");m_In[X_SHUTTLE_2_EJECTOR_PRESSURE_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_VACCUM_ON_SENSOR].m_strIOName=_T("X_SHUTTLE_2_VACCUM_ON_SENSOR");m_In[X_SHUTTLE_2_VACCUM_ON_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	m_In[X_SHUTTLE_2_FPCB_VACCUM_ON_SENSOR].m_strIOName=_T("X_SHUTTLE_2_FPCB_VACCUM_ON_SENSOR");m_In[X_SHUTTLE_2_FPCB_VACCUM_ON_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_ONIZER_2_PRESSURE_SENSOR].m_strIOName=_T("X_ONIZER_2_PRESSURE_SENSOR");m_In[X_ONIZER_2_PRESSURE_SENSOR].m_Check=CIOParam::CHECK_TYPE_A;
	//m_In[X_IONIZER_2_ALARM].m_strIOName=_T("X_IONIZER_2_ALARM");m_In[X_IONIZER_2_ALARM].m_Check=CIOParam::CHECK_TYPE_A;

}

void CIOParamBank::InitializeIOParam_OUT()
{
	//Y0000~X000F
	m_Out[Y_FRONT_DOOR1_LOCK_ONOFF].m_strIOName=_T("Y_FRONT_DOOR1_LOCK_ONOFF");m_Out[Y_FRONT_DOOR1_LOCK_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_FRONT_DOOR2_LOCK_ONOFF].m_strIOName=_T("Y_FRONT_DOOR2_LOCK_ONOFF");m_Out[Y_FRONT_DOOR2_LOCK_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_RIGNT_DOOR_LOCK_ONOFF].m_strIOName=_T("Y_RIGNT_DOOR_LOCK_ONOFF");m_Out[Y_RIGNT_DOOR_LOCK_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_BACK_DOOR1_LOCK_ONOFF].m_strIOName=_T("Y_BACK_DOOR1_LOCK_ONOFF");m_Out[Y_BACK_DOOR1_LOCK_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_LIGHT_CURTAIN_MUTING_LAMP].m_strIOName=_T("Y_SHUTTLE_1_LIGHT_CURTAIN_MUTING_LAMP");m_Out[Y_SHUTTLE_1_LIGHT_CURTAIN_MUTING_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_LIGHT_MUTING_ON_TO_SNC].m_strIOName=_T("Y_SHUTTLE_1_LIGHT_MUTING_ON_TO_SNC");m_Out[Y_SHUTTLE_1_LIGHT_MUTING_ON_TO_SNC].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_2_LIGHT_CURTAIN_MUTING_LAMP].m_strIOName=_T("Y_SHUTTLE_2_LIGHT_CURTAIN_MUTING_LAMP");m_Out[Y_SHUTTLE_2_LIGHT_CURTAIN_MUTING_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_2_LIGHT_MUTING_ON_TO_SNC].m_strIOName=_T("Y_SHUTTLE_2_LIGHT_MUTING_ON_TO_SNC");m_Out[Y_SHUTTLE_2_LIGHT_MUTING_ON_TO_SNC].m_Check=CIOParam::CHECK_TYPE_A;
	//m_Out[Y_PDT_3_LIGHT_CURTAIN_MUTING_LAMP].m_strIOName=_T("Y_PDT_3_LIGHT_CURTAIN_MUTING_LAMP");m_Out[Y_PDT_3_LIGHT_CURTAIN_MUTING_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	//m_Out[Y_PDT_3_LIGHT_MUTING_ON_TO_SNC].m_strIOName=_T("Y_PDT_3_LIGHT_MUTING_ON_TO_SNC");m_Out[Y_PDT_3_LIGHT_MUTING_ON_TO_SNC].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_OP_RESET_LAMP].m_strIOName=_T("Y_OP_RESET_LAMP");m_Out[Y_OP_RESET_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_VACCUM_ON_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_1_VACCUM_ON_SW_LAMP");m_Out[Y_SHUTTLE_1_VACCUM_ON_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_VACCUM_OFF_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_1_VACCUM_OFF_SW_LAMP");m_Out[Y_SHUTTLE_1_VACCUM_OFF_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_PATTERN_BACK_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_1_PATTERN_BACK_SW_LAMP");m_Out[Y_SHUTTLE_1_PATTERN_BACK_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_PATTERN_NEXT_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_1_PATTERN_NEXT_SW_LAMP");m_Out[Y_SHUTTLE_1_PATTERN_NEXT_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_PATTERN_ONOFF_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_1_PATTERN_ONOFF_SW_LAMP");m_Out[Y_SHUTTLE_1_PATTERN_ONOFF_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	
	//Y0010~Y001F
	m_Out[Y_SHUTTLE_2_VACCUM_ON_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_2_VACCUM_ON_SW_LAMP");m_Out[Y_SHUTTLE_2_VACCUM_ON_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_2_VACCUM_OFF_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_2_VACCUM_OFF_SW_LAMP");m_Out[Y_SHUTTLE_2_VACCUM_OFF_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_2_PATTERN_BACK_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_2_PATTERN_BACK_SW_LAMP");m_Out[Y_SHUTTLE_2_PATTERN_BACK_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_2_PATTERN_NEXT_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_2_PATTERN_NEXT_SW_LAMP");m_Out[Y_SHUTTLE_2_PATTERN_NEXT_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_2_PATTERN_ONOFF_SW_LAMP].m_strIOName=_T("Y_SHUTTLE_2_PATTERN_ONOFF_SW_LAMP");m_Out[Y_SHUTTLE_2_PATTERN_ONOFF_SW_LAMP].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_HOT_LINE_MTP_ALIVE].m_strIOName=_T("Y_HOT_LINE_MTP_ALIVE");m_Out[Y_HOT_LINE_MTP_ALIVE].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_HOT_LINE_MTP_EMERGENCY].m_strIOName=_T("Y_HOT_LINE_MTP_EMERGENCY");m_Out[Y_HOT_LINE_MTP_EMERGENCY].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_HOT_LINE_MTP_NET_READY].m_strIOName=_T("Y_HOT_LINE_MTP_NET_READY");m_Out[Y_HOT_LINE_MTP_NET_READY].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_HOT_LINE_MTP_DOOR_OPEN].m_strIOName=_T("Y_HOT_LINE_MTP_DOOR_OPEN");m_Out[Y_HOT_LINE_MTP_DOOR_OPEN].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_HOT_LINE_MTP_INTERLOCK].m_strIOName=_T("Y_HOT_LINE_MTP_INTERLOCK");m_Out[Y_HOT_LINE_MTP_INTERLOCK].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_HOT_LINE_MTP_INTERACTIVE_2].m_strIOName=_T("Y_HOT_LINE_MTP_INTERACTIVE_2");m_Out[Y_HOT_LINE_MTP_INTERACTIVE_2].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_HOT_LINE_MTP_INTERACTIVE_3].m_strIOName=_T("Y_HOT_LINE_MTP_INTERACTIVE_3");m_Out[Y_HOT_LINE_MTP_INTERACTIVE_3].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_HOT_LINE_MTP_SUB_EMO].m_strIOName=_T("Y_HOT_LINE_MTP_SUB_EMO");m_Out[Y_HOT_LINE_MTP_SUB_EMO].m_Check=CIOParam::CHECK_TYPE_A;
	
	//Y0020~X002F
	m_Out[Y_TOWER_LAMP_RED].m_strIOName=_T("Y_TOWER_LAMP_RED");m_Out[Y_TOWER_LAMP_RED].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_TOWER_LAMP_YELLOW].m_strIOName=_T("Y_TOWER_LAMP_YELLOW");m_Out[Y_TOWER_LAMP_YELLOW].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_TOWER_LAMP_GREEN].m_strIOName=_T("Y_TOWER_LAMP_GREEN");m_Out[Y_TOWER_LAMP_GREEN].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_BUZZER_K1].m_strIOName=_T("Y_BUZZER_K1");m_Out[Y_BUZZER_K1].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_BUZZER_K2].m_strIOName=_T("Y_BUZZER_K2");m_Out[Y_BUZZER_K2].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_BUZZER_K3].m_strIOName=_T("Y_BUZZER_K3");m_Out[Y_BUZZER_K3].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_BUZZER_K4].m_strIOName=_T("Y_BUZZER_K4");m_Out[Y_BUZZER_K4].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_BUZZER_K5].m_strIOName=_T("Y_BUZZER_K5");m_Out[Y_BUZZER_K5].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_TILTING_DOWN].m_strIOName=_T("Y_SHUTTLE_1_TILTING_DOWN");m_Out[Y_SHUTTLE_1_TILTING_DOWN].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_1_TILTING_UP].m_strIOName=_T("Y_SHUTTLE_1_TILTING_UP");m_Out[Y_SHUTTLE_1_TILTING_UP].m_Check=CIOParam::CHECK_TYPE_A;
	
	//Y0030~X003F
	m_Out[Y_SHUTTLE1_VACCUM_ONOFF].m_strIOName=_T("Y_SHUTTLE1_VACCUM_ONOFF");m_Out[Y_SHUTTLE1_VACCUM_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE1_BLOW_ONOFF].m_strIOName=_T("Y_SHUTTLE1_BLOW_ONOFF");m_Out[Y_SHUTTLE1_BLOW_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE1_FPCB_VACCUM_ONOFF].m_strIOName=_T("Y_SHUTTLE1_FPCB_VACCUM_ONOFF");m_Out[Y_SHUTTLE1_FPCB_VACCUM_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE1_FPCB_BLOW_ONOFF].m_strIOName=_T("Y_SHUTTLE1_FPCB_BLOW_ONOFF");m_Out[Y_SHUTTLE1_FPCB_BLOW_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_IONIZER_1_AIR_ONOFF].m_strIOName=_T("Y_IONIZER_1_AIR_ONOFF");m_Out[Y_IONIZER_1_AIR_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_IONIZER_1_POWER_ONOFF].m_strIOName=_T("Y_IONIZER_1_POWER_ONOFF");m_Out[Y_IONIZER_1_POWER_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SIGNAL_PC1_RESET].m_strIOName=_T("Y_SIGNAL_PC1_RESET");m_Out[Y_SIGNAL_PC1_RESET].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SIGNAL_PC2_RESET].m_strIOName=_T("Y_SIGNAL_PC2_RESET");m_Out[Y_SIGNAL_PC2_RESET].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE2_VACCUM_ONOFF].m_strIOName=_T("Y_SHUTTLE2_VACCUM_ONOFF");m_Out[Y_SHUTTLE2_VACCUM_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE2_BLOW_ONOFF].m_strIOName=_T("Y_SHUTTLE2_BLOW_ONOFF");m_Out[Y_SHUTTLE2_BLOW_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE2_FPCB_VACCUM_ONOFF].m_strIOName=_T("Y_SHUTTLE2_FPCB_VACCUM_ONOFF");m_Out[Y_SHUTTLE2_FPCB_VACCUM_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE2_FPCB_BLOW_ONOFF].m_strIOName=_T("Y_SHUTTLE2_FPCB_BLOW_ONOFF");m_Out[Y_SHUTTLE2_FPCB_BLOW_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_IONIZER_2_AIR_ONOFF].m_strIOName=_T("Y_IONIZER_2_AIR_ONOFF");m_Out[Y_IONIZER_2_AIR_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_IONIZER_2_POWER_ONOFF].m_strIOName=_T("Y_IONIZER_2_POWER_ONOFF");m_Out[Y_IONIZER_2_POWER_ONOFF].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_2_TILTING_DOWN].m_strIOName=_T("Y_SHUTTLE_2_TILTING_DOWN");m_Out[Y_SHUTTLE_2_TILTING_DOWN].m_Check=CIOParam::CHECK_TYPE_A;
	m_Out[Y_SHUTTLE_2_TILTING_UP].m_strIOName=_T("Y_SHUTTLE_2_TILTING_UP");m_Out[Y_SHUTTLE_2_TILTING_UP].m_Check=CIOParam::CHECK_TYPE_A;

}

CIOParam CIOParamBank::GetInputIOParma(INPUT_ID ID)
{
	return m_In[ID];
}

CIOParam CIOParamBank::GetOutputIOParma(OUTPUT_ID ID)
{
	return m_Out[ID];
}

