// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "actqj71e71tcp.h"

/////////////////////////////////////////////////////////////////////////////
// CActqj71e71tcp

IMPLEMENT_DYNCREATE(CActqj71e71tcp, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CActqj71e71tcp properties

/////////////////////////////////////////////////////////////////////////////
// CActqj71e71tcp operations
