//////////////////////////////////////////////////////////////////////////
// Error Pos Number
//////////////////////////////////////////////////////////////////////////
enum
{	
	ERR_NONE = 0,
	ERR_PCB_CONTACT1_MARK_FAIL,
	ERR_PCB_CONTACT2_MARK_FAIL,
	ERR_PCB_CONTACT3_MARK_FAIL,
	ERR_PCB_CONTACT4_MARK_FAIL,
	ERR_PCB_CONTACT1_MARK_SCORE_FAIL,
	ERR_PCB_CONTACT2_MARK_SCORE_FAIL,
	ERR_PCB_CONTACT3_MARK_SCORE_FAIL,
	ERR_PCB_CONTACT4_MARK_SCORE_FAIL,
	ERR_FPC_CONTACT1_MARK_FAIL,
	ERR_FPC_CONTACT2_MARK_FAIL,
	ERR_FPC_CONTACT3_MARK_FAIL,
	ERR_FPC_CONTACT4_MARK_FAIL,
	ERR_FPC_CONTACT1_MARK_SCORE_FAIL,
	ERR_FPC_CONTACT2_MARK_SCORE_FAIL,
	ERR_FPC_CONTACT3_MARK_SCORE_FAIL,
	ERR_FPC_CONTACT4_MARK_SCORE_FAIL,	
	ERR_CONTACT1_ALIGN_REVISION_FAIL,
	ERR_CONTACT2_ALIGN_REVISION_FAIL,
	ERR_CONTACT3_ALIGN_REVISION_FAIL,
	ERR_CONTACT4_ALIGN_REVISION_FAIL,

	ERR_EMO_SWITCH_ON = 21,
	ERR_DOOR_OPEN,
	ERR_CONTACT1_UP,
	ERR_CONTACT2_UP,
	ERR_CONTACT3_UP,
	ERR_CONTACT4_UP,
	ERR_CONTACT1_DOWN,	// 구현불가
	ERR_CONTACT2_DOWN,	// 구현불가
	ERR_CONTACT3_DOWN,	// 구현불가
	ERR_CONTACT4_DOWN,	// 구현불가
	ERR_WT_PANELCHK,
	ERR_TOP_CLAMP_ON,
	ERR_TOP_CLAMP_OFF,
	ERR_AREA_SENSOR,
	ERR_MAIN_POWER,

	ERR_VISION_COUNT_OVER = 40,
	ERR_INSPECTION_RESULT_FAIL,
	ERR_HOLD_RESULT,
	ERR_INSPECTION_FAIL_COUNT,
	ERR_UNLIGHTING_INSPECTION_FAIL,

	ERR_1XCONTACT_MOTOR_MOVING = 50,
	ERR_1YCONTACT_MOTOR_MOVING,
	ERR_2XCONTACT_MOTOR_MOVING,
	ERR_2YCONTACT_MOTOR_MOVING,
	ERR_3XCONTACT_MOTOR_MOVING,
	ERR_3YCONTACT_MOTOR_MOVING,
	ERR_4XCONTACT_MOTOR_MOVING,
	ERR_4YCONTACT_MOTOR_MOVING,
	ERR_TILTING_MOTOR_MOVING,
	ERR_PIN_Z_MOTOR_MOVING,
	// 추후에 추가될 지도 모르는 축들의 에러는 여기에..
	ERR_CONTACT_INIT_ERROR = 60,

	ERR_CONTACT_CRASH_POS = 70,
	ERR_UNLOADER_DISCHARGE_TIMEOUT,
	ERR_MOTOR_HOMEING_FAIL,
	ERR_PANELDATA_RECEIVE_FAIL,
	ERR_CONTACT_DOWN_MOVING_STAGE,
	ERR_HANDLER_CRASH_POS,
	ERR_HANDLER_POS_TIMEOUT,

	// NonStop Error
	ERR_NON_STOP_DEVICE_RECEIVE = 80,	// Non Stop Model Change시 Device ID를 못 받았을 경우
	ERR_NON_STOP_DEVICE_MATCH,			// Non Stop Model Change시 신규 DeviceID가 들어올 경우(GetDoc()->m_bUseAutoCreate 미사용시)

	// Check Message
	CHK_MOTION_INITIALIZE = 201,	// 원점 안잡고 START 했을 때
	CHK_MOTION_READY,				// Motor 이동중이나 Manual Sequence 동작 중에 START했을 때
	CHK_PCB_CHANGE,					// Non Stop Model Change중 PCB 교체 요청
	CHK_UNLOAD_COMP,


	CHK_INSP_COUNT,					// 검사 10매 이상이면 Check할수 있도록 Message띄움 [12/1/2009 JJH-RomanticBoy]

	//AutoTune //  [6/11/2009 janghan]
	ERR_AUTOTUNE = 300,
	ERR_AUTOTUNE_MOVE_CENTER,
	ERR_AUTOTUNE_FOV_OUT,
	ERR_AUTOTUNE_MARK_LINE_BAD,

	ERR_UNLD_COMMUNICATION_CLEAR = 400,

	ERR_CANCEL = 999
};
