// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "lbl_blu.h"

/////////////////////////////////////////////////////////////////////////////
// CLbl_blu

IMPLEMENT_DYNCREATE(CLbl_blu, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CLbl_blu properties

/////////////////////////////////////////////////////////////////////////////
// CLbl_blu operations
