// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "prev_port.h"

/////////////////////////////////////////////////////////////////////////////
// CPrev_port

IMPLEMENT_DYNCREATE(CPrev_port, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CPrev_port properties

/////////////////////////////////////////////////////////////////////////////
// CPrev_port operations
