// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "xnetctrl.h"

/////////////////////////////////////////////////////////////////////////////
// CXnetctrl1

IMPLEMENT_DYNCREATE(CXnetctrl1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CXnetctrl1 properties

/////////////////////////////////////////////////////////////////////////////
// CXnetctrl1 operations
