// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ieditx1.h"

/////////////////////////////////////////////////////////////////////////////
// CIeditx1

IMPLEMENT_DYNCREATE(CIeditx1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIeditx1 properties

/////////////////////////////////////////////////////////////////////////////
// CIeditx1 operations
