// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ilabelx2.h"

/////////////////////////////////////////////////////////////////////////////
// CIlabelx2

IMPLEMENT_DYNCREATE(CIlabelx2, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIlabelx2 properties

/////////////////////////////////////////////////////////////////////////////
// CIlabelx2 operations
