// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "iledroundx1.h"

/////////////////////////////////////////////////////////////////////////////
// CIledroundx1

IMPLEMENT_DYNCREATE(CIledroundx1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIledroundx1 properties

/////////////////////////////////////////////////////////////////////////////
// CIledroundx1 operations
