// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "iledrectanglex1.h"

/////////////////////////////////////////////////////////////////////////////
// CIledrectanglex1

IMPLEMENT_DYNCREATE(CIledrectanglex1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIledrectanglex1 properties

/////////////////////////////////////////////////////////////////////////////
// CIledrectanglex1 operations
