// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "ipercentbarx1.h"

/////////////////////////////////////////////////////////////////////////////
// CIpercentbarx1

IMPLEMENT_DYNCREATE(CIpercentbarx1, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIpercentbarx1 properties

/////////////////////////////////////////////////////////////////////////////
// CIpercentbarx1 operations
