// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "iswitchledx_remote.h"

/////////////////////////////////////////////////////////////////////////////
// CIswitchledx_remote

IMPLEMENT_DYNCREATE(CIswitchledx_remote, CWnd)

/////////////////////////////////////////////////////////////////////////////
// CIswitchledx_remote properties

/////////////////////////////////////////////////////////////////////////////
// CIswitchledx_remote operations
